### ISSUE TITLE
How can I Train my own Random Forest regressor

### ISSUE THREAD

**Issue by yanxurui** [playerkk/drfi_matlab#1]
### How can I Train my own regressor If I have a dataset of 20 images.

In **train/trainSameLabelClassifier.m**

```
same_label_classifier = train_boosted_dt_2c(trn_edata, [], trn_elab, 200, 20);
...
regressor = regRF_train( feat, lab, 200, 12, opt );
```

what shoud the 200,20,12 be?

and also in **train/my_trainSegmentSaliencyRegressor.m**

```
num_tree = 200;
mtry = 15;
```

looking forward your reply.

**Comment by playerkk** [comment]
1. For boosted decision trees, 200 is the number of decision trees and 20 is the maximum number of nodes in each tree. 
2. For random forest regressor, 200 is also the number of trees. 12 is the number of features randomly sampled to train each node in the tree.

These parameters might be data dependent. A good way is to set them according to the validation error.
